
function preCacheResources(context)
    PrecacheResource("model_folder", "models/items/furion", context)
    PrecacheResource("particle_folder", "econ/items/natures_prophet", context)

    PrecacheResource("model_folder", "models/items/shredder", context)
    PrecacheResource("particle_folder", "econ/items/timbersaw", context)

    PrecacheResource("model_folder", "models/items/batrider", context)
    PrecacheResource("particle_folder", "econ/items/batrider", context)

    PrecacheResource("model_folder", "models/items/pudge", context)
    PrecacheResource("particle_folder", "econ/items/pudge", context)

    PrecacheResource("model_folder", "particles/units/heroes/hero_techies", context)
    PrecacheResource("particle_folder", "particles/units/heroes/hero_techies", context)

    PrecacheResource("model_folder", "models/items/treant", context)
    PrecacheResource("particle_folder", "econ/items/treant", context)

    -- required for cosmetic shit
    PrecacheResource( "model", "models/development/invisiblebox.vmdl", context)
    -- building helper
    PrecacheResource("particle_folder", "particles/buildinghelper", context)


    PrecacheResource("model", "models/buildings/building_plain_reference.vmdl", context)
    PrecacheResource("model", "models/buildings/building_plain_reference.vmdl", context)
    PrecacheResource("model", "models/courier/f2p_courier/f2p_courier_flying.vmdl", context)
    PrecacheResource("model", "models/creeps/lane_creeps/creep_radiant_ranged/radiant_ranged.vmdl", context)
    PrecacheResource("model", "models/heroes/furion/treant.vmdl", context)
    PrecacheResource("model", "models/items/courier/shagbark/shagbark.vmdl", context)
    PrecacheResource("model", "models/items/courier/tinkbot/tinkbot.vmdl", context)
    PrecacheResource("model", "models/items/furion/treant/father_treant/father_treant.vmdl", context)
    PrecacheResource("model", "models/items/furion/treant/primeval_treant/primeval_treant.vmdl", context)
    PrecacheResource("model", "models/items/furion/treant/shroomling_treant/shroomling_treant.vmdl", context)
    PrecacheResource("model", "models/items/furion/treant/treant_cis/treant_cis.vmdl", context)
    PrecacheResource("model", "models/props_rock/riveredge_rock006a.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_ancient_fountain001.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_ancient_fountain001_water.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_ancient_lightbeams.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_barracks_melee001.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_barracks_melee002.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_barracks_melee002_lvl1.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_barracks_melee002_lvl2.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_base_wall006.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_fountain001.vmdl", context)
    PrecacheResource("model", "models/props_structures/good_statue010.vmdl", context)
    PrecacheResource("model", "models/props_structures/tower_good_dest_lvl1.vmdl", context)
    PrecacheResource("particle", "particles/base_attacks/ranged_goodguy.vpcf", context)
    PrecacheResource("particle", "particles/dire_fx/tower_bad_face_end_explode.vpcf", context)

    
    PrecacheResource("sound", "Creep_Siege_Radiant.Destruction", context)
    PrecacheResource("sound", "item_handofmidas", context)
    PrecacheResource("sound", "sound/items/item_handofmidas.vsnd", context)
    PrecacheResource("sound", "sound/items/item_handofmidas.wav", context)
    PrecacheResource("sound", "sounds/items/item_handofmidas.vsnd", context)

    
    PrecacheResource("particle", "particles/econ/courier/courier_greevil_blue/courier_greevil_blue_ambient_3.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_greevil_green/courier_greevil_green_ambient_3.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_roshan_frost/courier_roshan_frost_ambient.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_shagbark/courier_shagbark_ambient.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_trail_04/courier_trail_04.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_trail_orbit/courier_trail_orbit_d.vpcf", context)
    PrecacheResource("particle", "particles/econ/events/coal/coal_projectile_explosion.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/maiden_crystal_nova_cowlofice.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/tinker/boots_of_travel/teleport_end_bots.vpcf", context)
    PrecacheResource("particle", "particles/items2_fx/smoke_of_deceit_buff.vpcf", context)
    PrecacheResource("particle", "particles/items2_fx/true_sight_debuff.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_axe/axe_battle_hunger_b.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_batrider/batrider_firefly.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_batrider/batrider_firefly_head.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_batrider/batrider_firefly_path.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_brewmaster/brewmaster_primal_split_fire_trail.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_brewmaster/brewmaster_primal_split_storm_trail_b.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_disruptor/disruptor_thunder_strike_buff.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_enchantress/enchantress_enchant_slow_grass_long.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_enchantress/enchantress_natures_attendants_heal_wispb.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_huskar/huskar_burning_spear_debuff.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_phoenix/phoenix_ambient_mane_blue.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_pugna/pugna_life_drain.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_razor/razor_static_link_beam.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_shredder/shredder_whirling_death.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_sven/sven_storm_bolt_projectile_explosion_trail.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_techies/techies_suicide.vpcf", context)
    PrecacheResource("particle", "particles/dire_fx/tower_bad_face_end_explode.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_greevil_green/courier_greevil_green_ambient_3.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_roshan_frost/courier_roshan_frost_ambient.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_shagbark/courier_shagbark_butterflies.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_trail_04/courier_trail_04.vpcf", context)
    PrecacheResource("particle", "particles/econ/courier/courier_trail_orbit/courier_trail_orbit_d.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/crystal_maiden/crystal_maiden_cowl_of_ice/maiden_crystal_nova_e_cowlofice.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/gyrocopter/hero_gyrocopter_gyrotechnics/gyro_guided_missile_explosion.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/tinker/boots_of_travel/teleport_end_bots.vpcf", context)
    PrecacheResource("particle", "particles/items2_fx/smoke_of_deceit_buff.vpcf", context)
    PrecacheResource("particle", "particles/items2_fx/true_sight_debuff.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_alchemist/alchemist_acid_spray_c.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_alchemist/alchemist_unstable_concoction_explosion.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_batrider/batrider_firefly_head.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_batrider/batrider_firefly_headglow.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_brewmaster/brewmaster_primal_split_fire_trail.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_brewmaster/brewmaster_primal_split_storm_trail_b.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_enchantress/enchantress_natures_attendants_heal_wispa.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_enchantress/enchantress_natures_attendants_heal_wispb.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_enchantress/enchantress_natures_attendants_heal_wispc.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_enchantress/enchantress_natures_attendants_heal_wispd.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_invoker/invoker_sun_strike.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_invoker/invoker_sun_strike_ground.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_pudge/pudge_rot.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_pugna/pugna_life_drain.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_shredder/shredder_whirling_death_spin_blades.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_sven/sven_storm_bolt_projectile_explosion_trail.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_techies/techies_suicide.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_wisp/wisp_ambient_d.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_wisp/wisp_ambient_f.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_wisp/wisp_ambient_h.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_wisp/wisp_tether.vpcf", context)


    PrecacheUnitByNameSync("npc_dota_beastmaster_hawk", context)
    PrecacheUnitByNameSync("npc_dota_creep_goodguys_ranged", context)
    PrecacheUnitByNameSync("npc_dota_goodguys_tower1_top", context)
    PrecacheUnitByNameSync("npc_dota_hero_abaddon", context)
    PrecacheUnitByNameSync("npc_dota_hero_alchemist", context)
    PrecacheUnitByNameSync("npc_dota_hero_antimage", context)
    PrecacheUnitByNameSync("npc_dota_hero_axe", context)
    PrecacheUnitByNameSync("npc_dota_hero_batrider", context)
    PrecacheUnitByNameSync("npc_dota_hero_beastmaster", context)
    PrecacheUnitByNameSync("npc_dota_hero_crystal_maiden", context)
    PrecacheUnitByNameSync("npc_dota_hero_furion", context)
    PrecacheUnitByNameSync("npc_dota_hero_gyrocopter", context)
    PrecacheUnitByNameSync("npc_dota_hero_invoker", context)
    PrecacheUnitByNameSync("npc_dota_hero_lina", context)
    PrecacheUnitByNameSync("npc_dota_hero_pudge", context)
    PrecacheUnitByNameSync("npc_dota_hero_rattletrap", context)
    PrecacheUnitByNameSync("npc_dota_hero_riki", context)
    PrecacheUnitByNameSync("npc_dota_hero_shredder", context)
    PrecacheUnitByNameSync("npc_dota_hero_techies", context)
    PrecacheUnitByNameSync("npc_dota_hero_treant", context)
    PrecacheUnitByNameSync("npc_dota_hero_vengefulspirit", context)
    PrecacheUnitByNameSync("npc_dota_hero_venomancer", context)
    PrecacheUnitByNameSync("npc_dota_hero_warlock", context)
end